spring.datasource:
  url: jdbc:mysql://localhost:3306/realperfect?autoReconnect=true&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
  username: root
  password: root
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy #change to real
            client-secret: dummy #change to real
            scope:
              - profile
              - openid
              - email
  mail:
    host: smtp.gmail.com
    port: 587
    username: <gmail-id>
    password: <gmail-app-password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          debug: true
  profiles:
    active: local
spring.servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 6MB


management:
  security:
    enabled: false

realtypics.storage.root: "D:/realperfect"

jwt:
  secret: 0CVV3xVlsnT4i9dnaRuEOunK7Za8avDO4UK9dLcQDMg2sHtHBO3BcS+mqMUwtUIQypnq74wYJv3dFEO3th93wWwTo8hAsPt/9TeVbdo5VASRzQFFmllOoRlJ3c/dh95HJIUIh3qoT181s93QVywg7I8nRaKwUj1gIOREMa5u36eWEQJ7GS6WJ0h0mLTu7/LuxMz8IwVaBbkKzZLyrb67faikzs5xt7zXDAIVpw==

server:
  websocket:
    port: 8081
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org:
      springframework:
        security=DEBUG: