spring.datasource:
  url: jdbc:mysql://localhost:3306/realperfect?autoReconnect=true&useSSL=false&serverTimezone=GMT
  username: root
  password: root
  driverClassName: com.mysql.cj.jdbc.Driver
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
spring.http:
  multipart:
    max-file-size: 5MB
    max-request-size: 6MB
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
realtypics.storage.root: "D:/realperfect"
